-- Completion: The War Within's mounts, pets and toys (item IDs). The game decides each one's zone from its
-- Mount or Pet Journal source, like Midnight's (Data/Collections.lua); the rest go to The War Within page.
-- GENERATED by Tools/gen_tww.py.

local _, ns = ...

ns.COLLECT_SETS = ns.COLLECT_SETS or {}
ns.COLLECT_SETS[#ns.COLLECT_SETS + 1] = { exp = "tww", name = "The War Within",
    mounts = {
    },
    pets = {
    },
    toys = {
    },
}
