-- Completion: every Midnight delve with its Sturdy Chests (Discoveries) and Stories achievements, entrance
-- and story notes. GENERATED by Tools/gen_delves.lua from the DelveStories addon. Do not edit by hand.
-- name = { map, chests = achievement, stories = achievement, at = { uiMap, x, y } or nil,
--          notes = { story name = what you do }, extra = { { n = name, d = what you do } } (not in the achievement) }
local _, ns = ...

ns.DELVE_INFO = {
    ["Collegiate Calamity"] = {
        map = 2547, chests = 61894, stories = 61726, zone = "eversong",
        at = { 2393, 40.76, 54.06 },
        notes = {
            ["Academy Under Siege"] = "Boss: Voidscorned Vagrant. A void invasion hits the Thalassian University. Close the portals and beat back Xal'atath's Devouring Host.",
            ["Faculty of Fear"] = "Boss: Infiltrator Garand. Twilight's Blade agents hide among the students. Use the Eye of Revelation to unmask them (suspects glow yellow, even through walls).",
            ["Invasive Glow"] = "Boss: Hydrangea. Lightbloom plants overrun the campus. A Grimgrow Deweeder kills the small ones outright; burn every Luminibulb patch on the main floor.",
            ["Academic Antitoxin"] = "Season 2. Help Sir Finley Mrrgglton brew an antidote to the Ula'tek poison: find his tomes, gather ingredients, cure the students. Fungal Pharmacon vials clear poison pools. The chest appears when you finish.",
        },
    },
    ["The Darkway"] = {
        map = 2525, chests = 61895, stories = 61728, zone = "eversong",
        at = { 2393, 39.30, 32.10 },
        notes = {
            ["Focusers Under Pressure"] = "Boss: Infiltrator Gulkat. The Twilight's Blade sabotages the ley lines under Silvermoon. Find the ley line focusers and carry them back to the middle of the delve.",
            ["Leyline Technician"] = "Boss: Infiltrator Gulkat. Realign the ley line conduits (Suramar style, but one tap per line, no puzzle) to power three focus crystals.",
            ["Ogre Powered"] = "Boss: Infiltrator Gulkat. The short one: reach the middle and kill 7 Unstable Aberrations (interrupt Arcane Deluge), then Gulkat.",
        },
        extra = {
            { n = "Eggsplosive Growth", d = "Boss: Replicating Venomborne. Season 2 Ula'tek story. Children of Ula'tek nest in the tunnels; click the Venom-Clogged Leyline pylons to blow up their eggs." },
        },
    },
    ["The Shadow Enclave"] = {
        map = 2502, chests = 61892, stories = 61727, zone = "eversong",
        at = { 2395, 45.40, 86.00 },
        notes = {
            ["Traitor's Due"] = "Boss: Lord Antenorian. Chase Lord Antenorian through the enclave: stop rituals, switch off void orbs, purge cultists. The same story you saw in the Eversong questline.",
            ["Mirror Shine"] = "Boss: Lord Antenorian. Carry mirrors to bounce light through the dark halls onto the Shadow Nexuses. Stay in the light or the grues get you. Light makes crits more likely for everyone.",
            ["Shadowy Supplies"] = "Boss: Lord Antenorian. Loot the Twilight's Blade's valuables: they drop from cultists and lie around the delve.",
            ["Basilisk Blitz"] = "Boss: Abominable Blunder. Season 2 Ula'tek story (guides call it Infiltrate and Ameliorate). Sneak through, kick Ula'tek summoners into the abyss and spike their cauldrons with odd ingredients.",
            ["Infiltrate and Ameliorate"] = "Boss: Abominable Blunder. Season 2 Ula'tek story (guides call it Infiltrate and Ameliorate). Sneak through, kick Ula'tek summoners into the abyss and spike their cauldrons with odd ingredients.",
        },
    },
    ["Parhelion Plaza"] = {
        map = 2545, chests = 61893, stories = 61725, zone = "queldanas",
        at = { 2424, 47.74, 41.58 },
        notes = {
            ["Bombing Run"] = "Boss: Gladius Slaurna. Carry an Improvised Arcane Device through void portals and blow up the portals on the other side. 40 seconds per carry, and you drop it in combat.",
            ["Holding the Line"] = "Boss: Gladius Slaurna. Defend the plaza from the Devouring Host with the Tempest Keep legendary weapons and rebuild the broken barricades.",
            ["March of the Arcane Brigade"] = "Boss: Gladius Slaurna. Wake Quel'Danas Sentinel machines; they run to the nearest void pylon and smash it.",
            ["March of the Arcane Parade"] = "Boss: Gladius Slaurna. Wake Quel'Danas Sentinel machines; they run to the nearest void pylon and smash it.",
            ["Caustic Crush"] = "Boss: Replicating Venomborne. Season 2 Ula'tek story. Stop the slime summoners; Fungal Pharmacon clears the way. Dodge the waves, they stun and hit hard.",
        },
    },
    ["Atal'Aman"] = {
        map = 2535, chests = 61863, stories = 61729, zone = "zulaman",
        at = { 2437, 24.80, 53.00 },
        notes = {
            ["Ritual Interrupted"] = "Boss: Spiritflayer Jin'Ma. The Vilebranch kidnapped Spiritpaw furbolgs for a ritual. Free them across the delve.",
            ["Toadly Unbecoming"] = "Boss: Spiritflayer Jin'Ma. Vilebranch hexers turn Amani trolls into frogs. Use the Vilebranch Hex Stick to change them back. A nod to old Zul'Aman, Mojo included.",
            ["Totem Annihilation"] = "Boss: Spiritflayer Jin'Ma. Smash the cursed totems at Akil'zon's shrine to free the Loa. The eagles fly you in from different sides.",
            ["Venomous Vapors"] = "Boss: Disciple of Vash'nik. Season 2 Ula'tek story. Marla gives you tools to clean up a poison infestation.",
        },
    },
    ["Twilight Crypts"] = {
        map = 2504, chests = 61896, stories = 61730, zone = "zulaman",
        at = { 2437, 25.40, 84.30 },
        notes = {
            ["Loosed Loa"] = "Boss: Blademaster Darza. Drink an Evasive Elixir and kill Skeleton Charmers and Vilebranch totems while dodging Mot'amra, the roaming Loa of Pestilence (big hit and knockback).",
            ["Party Crasher"] = "Boss: Blademaster Darza. Escort a hurt Explorer's League delver deeper in: bear traps everywhere, kill the summoners, pull levers to open each level.",
            ["Trapped!"] = "Boss: Blademaster Darza. A maze of traps and levers; rescue the Twilight's Blade's hostages.",
            ["Why'd it Have to Be Snakes?"] = "Boss: Replicating Venomborne. Season 2 Ula'tek story with Harrison Jones, hunting snake relics. Step on snakes (they explode) and use Fungal Pharmacon on poison pools.",
        },
    },
    ["The Grudge Pit"] = {
        map = 2510, chests = 61897, stories = 61724, zone = "harandar",
        at = { 2413, 70.50, 64.90 },
        notes = {
            ["Arena Champion"] = "Boss: Gyrospore. Fight wave after wave in the sporeling arena championship, with Sporbits helping, until the champion steps in.",
            ["Dastardly Rotstalk"] = "Boss: Mycomight. Play the arena heel: punt fans, beat their favourite fighters and taunt the crowd (you can move while taunting).",
            ["Lightbloom Invasion"] = "Boss: Brightthorn. Hold off Lightbloom waves. Free fighters to blow up the enemy spawn points and help build defenses.",
            ["Fungal Pharmacon"] = "Boss: Replicating Venomborne. Season 2 Ula'tek story. Grab four Fungal Pharmacons (blue on the minimap) and break the Ula'tek totem pillars.",
        },
    },
    ["The Gulf of Memory"] = {
        map = 2505, chests = 61898, stories = 61731, zone = "harandar",
        at = { 2413, 36.30, 49.20 },
        notes = {
            ["Descent of the Haranir"] = "Boss: Mul'tha'ul. Relive the Haranir's journey down: light the giant candles, deal with kobolds, find odd treasures. Darkness raises your damage taken. The same story as in the Harandar questline.",
            ["Alnmoth Munchies"] = "Boss: Lumenia. Your extra button summons an Alnmoth Storm that eats Lightbloom bushes and hurts Rutaani. You can move and cast while it channels.",
            ["Sporasaur Special"] = "Boss: Lumenia. Kill the souped-up Lightbloom Sporasaurs. Kick the Sporbits they spawn (green circle) back at them to break their shield.",
        },
    },
    ["Sunkiller Sanctum"] = {
        map = 2528, chests = 61899, stories = 61732, zone = "voidstorm",
        at = { 2405, 54.80, 47.00 },
        notes = {
            ["Core of the Problem"] = "Boss: Esuritus. Use the portal network to grab the energized cores before the Domanaar do. Each core gives stacking speed and damage reduction.",
            ["The Gravitational Effect"] = "Boss: Esuritus. Ride the micro-singularities' gravity around the sanctum and shut down the shields powering the boss.",
            ["Not What I Expected"] = "A Lightbloom experiment went wrong: kill both void and Lightbloom enemies. It ends when the three Corrupted Umbraroots die.",
        },
    },
    ["Shadowguard Point"] = {
        map = 2506, chests = 61900, stories = 61733, zone = "voidstorm",
        at = { 2405, 37.38, 47.70 },
        notes = {
            ["Calamitous"] = "Boss: Chief-Arcanist Patram. Pick up Arcane Charges (faster movement) and overload the Void Stabilizers. The blasts kill ethereals, and you too if you stand in them.",
            ["Captured Wildlife"] = "Boss: Chief-Arcanist Patram. Free the void-touched beasts the ethereals caught. They leave you alone, but keep out of their area attacks.",
            ["Stolen Mana"] = "Boss: Chief-Arcanist Patram. One simple goal: shoot the mana containers with a borrowed rifle until the boss opens up.",
            ["Basilisk Blitz"] = "Boss: Disciple of Vash'nik. Season 2 Ula'tek story, on the ethereals' side this time. Redirect shields and kill the basilisks feeding the boss; touching an active barrier stuns you.",
        },
    },
    ["Gnarldor Isle"] = {
        map = 2635, chests = 63170, stories = 63437, zone = "coiled",
        at = { 2512, 64.45, 77.73 },
        notes = {
            ["Olds and Ends"] = "Boss: Gralka Snake-Eater. With Tormunda, rescue 8 captured Tortollan elders and pick up the stolen relics (drops from Djaradin or loose on the ground).",
            ["Speaking Their Language"] = "Boss: Gralka Snake-Eater. With Artolla, rescue 3 turtles and the stolen supplies, then ride a War Turtle and kill 50 Djaradin before the boss.",
            ["Minchi's Osseous Adventure"] = "Boss: Osseous Amalgamation. With young Minchi: click 6 bone piles (each starts a wave), take 6 hearts from Djaradin corpses, then do the ritual on the bridge. The boss plays like Lord Marrowgar.",
        },
    },
    ["The Ring of Glory"] = {
        map = 2633, chests = 63171, stories = 63436, zone = "coiled",
        notes = {
            ["Open Night"] = "Boss: Drakta. Beat the glory-seekers, then a Ring of Blood style ladder of harder fights up to the arena champion.",
            ["Game Day"] = "Boss: Drakta. Ghostly Headball: kill mobs for skulls and kick them into the pillars. Up to three goals per pillar; masks start guarding after a few.",
            ["Adopt-a-thon"] = "Boss: Gnok. Rescue skittish little animals from the fights. They run off (and pull extra mobs); the snacks lying around calm them.",
        },
    },
}

ns.DELVE_LOREMASTER = 61741   -- Delve Loremaster: Midnight, the meta of every Stories achievement
