-- Completion: where the mounts, pets and toys with no treasure, rare or vendor source come from.
-- GENERATED by Tools/make_sources.py (dropped by, contained in, quest and achievement rewards, quest givers).
-- t = how to get it, a = the achievement that rewards it, at = { {uiMap, x, y}, ... }
local _, ns = ...

ns.ITEM_SOURCES = {
    [239101] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Voidcrawler
    [240840] = { t = "Reward from the achievement Midnight Dungeon Hero", a = 61567 }, -- Niblet
    [243146] = { t = "Reward from the quest Violent Conclusions (from Kelia Everglow)", at = { { 2405, 41.2, 61.4 } } }, -- Ren'dorei Struggle
    [246594] = { t = "Reward from the achievement Two Minutes to Midnight", a = 42300 }, -- Light-Forged Mechsuit
    [246731] = { t = "Reward from the quest History Lesson (from Orweyna)" }, -- Dusk Grimlynx
    [246736] = { t = "Reward from the achievement Allied Race: Haranir", a = 61506 }, -- Ivory Grimlynx
    [248485] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Wormhole Generator: Quel'Thalas
    [250135] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Akil Fledgling
    [250136] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Rootling Nester
    [250137] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Mud Potadpole
    [250138] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Violet Chick
    [250139] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Ebon Snapling
    [250140] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Swamp Biter
    [250142] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Azure Sporebat
    [250143] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Dragonhawk Mosswing
    [250145] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Pangolil
    [250146] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Gloom Toad
    [250147] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Silkcrawler
    [250148] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Blistercreepling
    [251001] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Vibrant Manaling
    [251002] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Nether Familiar
    [251003] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Wrathful Wyrm
    [251004] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Striped Snakebiter
    [251005] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Riftblade Familiar
    [251491] = { t = "Reward from the achievement Old World Family Battler", a = 61094 }, -- Magical Pet Clicker
    [252011] = { t = "Reward from the achievement Light Up the Night", a = 62386 }, -- Brilliant Petalwing
    [253629] = { t = "Reward from the quest The Arcantina (from Kurdran Wildhammer)", at = { { 2393, 40.4, 66.0 } } }, -- Personal Key to the Arcantina
    [257143] = { t = "Reward from the quest From Darkness, Light (from Lady Liadrin)", at = { { 2424, 52.4, 46.0 } } }, -- Peridot Dragonhawk
    [257144] = { t = "Reward from the achievement Life of the Party", a = 62190 }, -- Umbral Dragonhawk
    [257145] = { t = "Reward from the achievement Midnight Glyph Hunter", a = 61584 }, -- Crimson Dragonhawk
    [257176] = { t = "Comes in Slayer's Duellum Trove" }, -- Duskbrute Harrower
    [257180] = { t = "Comes in Victorious Stormarion Pinnacle Cache, Victorious Stormarion Cache" }, -- Reins of the Contained Stormarion Defender
    [257193] = { t = "Reward from the achievement Prey: Nightmare Mode III", a = 42703 }, -- Preyseeker's Nightmare
    [257199] = { t = "Reward from the achievement Glory of the Midnight Delver", a = 61906 }, -- Giganto Manis
    [257225] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Witherbark Warbear Harness
    [257240] = { t = "Reward from the quest Relinquishing Relics (from Alonsus Faol)", at = { { 2424, 52.4, 55.8 } } }, -- Relinquished Scarlet Charger
    [257502] = { t = "Reward from the achievement Galactic Combatant", a = 61403 }, -- Vicious Snaplizard
    [257504] = { t = "Reward from the achievement Galactic Combatant", a = 61405 }, -- Vicious Snaplizard
    [257736] = { t = "Reward from the quest March on Quel'Danas (from Arator)" }, -- Lightcalled Hearthstone
    [258122] = { t = "Reward from the quest The Battle of the Bridge (from Arator)", at = { { 2393, 45.2, 70.2 } } }, -- Emerald Hatchling
    [258660] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Silvermoon Broom
    [258737] = { t = "Reward from the achievement Family Battler of Kalimdor", a = 61051 }, -- Moon Darter
    [260228] = { t = "Reward from the achievement Gladiator: Midnight Season 1", a = 61188 }, -- Galactic Gladiator's Goredrake
    [260231] = { t = "Found in Challenger's Cache" }, -- Lucent Hawkstrider
    [260233] = { t = "Reward from the quest The Battle of the Bridge (from Arator)", at = { { 2393, 45.2, 70.2 } } }, -- Emerald Hawkstrider
    [260306] = { t = "Reward from the quest The Empty Cradle (from Aksem)", at = { { 2413, 53.4, 49.4 } } }, -- Distorted Memory
    [260585] = { t = "Reward from the quest O.K. Bloomer (from Hannan)", at = { { 2413, 37.4, 72.4 }, { 2413, 41.6, 67.8 } } }, -- Linda the Lucky
    [260697] = { t = "Reward from the achievement Staring Into The Void", a = 62385 }, -- Lab-Grown Stormray
    [260705] = { t = "Reward from the quest Re-Hydra-ted (from Ney'tar)", at = { { 2413, 69.4, 50.6 } } }, -- Assistant Botanist Leafy
    [260887] = { t = "Reward from the achievement Glory of the Midnight Raider", a = 61380 }, -- Tenebrous Harrower
    [260922] = { t = "Reward from the quest Mighty and Superior (from Ravenia)", at = { { 2405, 52.0, 67.4 } } }, -- Fidoficus
    [260942] = { t = "Found in Grand Line Treasure, Patient Treasure", at = { { 2413, 31.0, 63.7 }, { 2413, 36.3, 81.0 }, { 2413, 36.6, 62.0 }, { 2405, 31.7, 66.5 }, { 2405, 31.9, 56.1 }, { 2405, 35.2, 46.0 } } }, -- Bubbly Snapling
    [262342] = { t = "Found in Pilfered Trunk, Abundantly Bountiful Heavy Trunk, Nemesis Strongbox", at = { { 2510, 43.5, 44.0 }, { 2510, 43.9, 42.3 }, { 2510, 58.8, 48.7 }, { 2633, 32.3, 55.8 }, { 2633, 33.0, 57.2 }, { 2510, 61.2, 48.9 } } }, -- Spormilian
    [262343] = { t = "Found in Hidden Trove, Bountiful Coffer", at = { { 2510, 43.8, 42.3 }, { 2510, 61.4, 50.3 }, { 2633, 32.4, 53.1 }, { 2510, 59.2, 51.2 }, { 2633, 32.0, 49.3 } } }, -- Treja'saka
    [262390] = { t = "Found in Pilfered Trunk, Abundantly Bountiful Heavy Trunk", at = { { 2510, 43.5, 44.0 }, { 2510, 43.9, 42.3 }, { 2510, 58.8, 48.7 }, { 2633, 32.3, 55.8 }, { 2633, 33.0, 57.2 }, { 2510, 59.7, 56.5 } } }, -- Sporbie
    [262391] = { t = "Found in Azta'rec Cache, Nullaeus Cache", at = { { 2510, 38.6, 47.5 }, { 2510, 39.2, 40.8 }, { 2510, 40.8, 53.9 }, { 2633, 25.1, 66.4 }, { 2633, 26.5, 64.3 }, { 2633, 27.0, 45.7 } } }, -- Ominous Dominus
    [262392] = { t = "Found in Pilfered Trunk, Abundantly Bountiful Heavy Trunk", at = { { 2510, 43.5, 40.7 }, { 2510, 43.9, 42.3 }, { 2510, 58.2, 49.7 }, { 2633, 32.1, 53.2 }, { 2633, 32.6, 51.3 }, { 2510, 43.5, 44.0 } } }, -- Nibblesworth
    [262394] = { t = "Found in Pilfered Trunk, Nemesis Strongbox", at = { { 2510, 43.5, 44.0 }, { 2510, 43.9, 42.3 }, { 2510, 58.8, 48.7 }, { 2633, 32.3, 55.8 }, { 2633, 33.0, 57.2 }, { 2510, 43.5, 40.7 } } }, -- Ziorg'pharon
    [262395] = { t = "Found in Pilfered Trunk, Abundantly Bountiful Heavy Trunk", at = { { 2510, 43.5, 44.0 }, { 2510, 43.9, 42.3 }, { 2510, 58.8, 48.7 }, { 2633, 32.3, 55.8 }, { 2633, 33.0, 57.2 }, { 2510, 43.5, 40.7 } } }, -- Hexed Bunny
    [262396] = { t = "Found in Pilfered Trunk, Nemesis Strongbox", at = { { 2510, 43.5, 44.0 }, { 2510, 43.9, 42.3 }, { 2510, 58.8, 48.7 }, { 2633, 32.3, 55.8 }, { 2633, 33.0, 57.2 }, { 2510, 43.5, 40.7 } } }, -- Lost Star
    [262620] = { t = "Reward from the achievement Midnight Keystone Master: Season 1", a = 61256 }, -- Calamitous Carrion
    [262621] = { t = "Reward from the achievement Midnight Keystone Legend: Season 1", a = 61258 }, -- Convalescent Carrion
    [262774] = { t = "Found in Netherstorm Structural Cage" }, -- Gortham
    [262914] = { t = "Found in Challenger's Cache" }, -- Spectral Hawkstrider
    [262999] = { t = "Reward from the quest Thief at Bark (from Luma)", at = { { 2395, 39.0, 38.4 } } }, -- Luma
    [263198] = { t = "Reward from the quest Lost in Light (from Kaliel Solaar)", at = { { 2395, 48.8, 76.6 } } }, -- Valdekar's Special
    [263222] = { t = "Reward from the achievement Let Me Solo Him: Nullaeus", a = 61799 }, -- Arcanovoid Construct
    [263579] = { t = "Reward from the achievement Treasures of Harandar", a = 61263 }, -- Vivacious Chloroceros
    [263871] = { t = "Reward from the quest Pet Wranglin' (from Hawkrancher Saman)", at = { { 2393, 41.8, 76.2 } } }, -- Holy Pet Leash
    [263975] = { t = "Reward from the achievement Illicit Rain: Five Stars", a = 62388 }, -- Feeling Fielder Mk. 7
    [264313] = { t = "Drops from Rotmire" }, -- Madcap Redcap
    [264367] = { t = "Drops from Rotmire" }, -- Mycomancer's Hearthspore
    [264413] = { t = "Reward from the quest Nulling Nullaeus (from Valeera Sanguinar)", at = { { 2393, 52.4, 78.0 } } }, -- Dominating Victory
    [264654] = { t = "Reward from the quest A Quiet Farewell (from Grieving Amani)", at = { { 2437, 45.3, 73.6 }, { 2437, 46.3, 72.0 } } }, -- Emberwing Hatchling
    [264672] = { t = "Drops from Fallen-King Salhadaar" }, -- Cosmic Ritual Stone
    [264695] = { t = "Reward from the achievement Treasures of Voidstorm", a = 62126 }, -- Interdimensional Parcel Signal
    [264892] = { t = "Comes in Slayer's Duellum Trove" }, -- Nova
    [265030] = { t = "Comes in Victorious Stormarion Pinnacle Cache, Victorious Stormarion Cache" }, -- Kai
    [265656] = { t = "Reward from the achievement Insurmountable Collection", a = 62096 }, -- Anu'shalla, Shadow's Guidance
    [267323] = { t = "Reward from the quest Darkspear Dash (from Kalaya)", at = { { 463, 46.8, 47.4 } } }, -- Troll Scroll of Rainbow Roll
    [267456] = { t = "Reward from the quest Scoot Along Now (from Drathen)", at = { { 2393, 44.8, 60.4 } } }, -- Lil' Scoots' Pillow
    [268557] = { t = "Reward from the quest Dead End (from Orweyna)", at = { { 2437, 44.4, 66.6 } } }, -- Akiki
    [268644] = { t = "Reward from the quest A Little Kindness (from Jelvik)", at = { { 2512, 61.0, 32.6 } } }, -- Zan
    [268695] = { t = "Reward from the achievement Craft Your World", a = 62400 }, -- Pin-o-Matic Camera
    [268717] = { t = "Reward from the achievement Treasures of Zul'Aman", a = 62125 }, -- Pango Plating
    [268728] = { t = "Found in Challenger's Cache" }, -- Saptor Salve
    [269028] = { t = "Reward from the achievement Treasures of Eversong Woods", a = 61960 }, -- Sootpaw
    [269240] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Luminous Sporeglider
    [269829] = { t = "Found in Void-Tainted Nest", at = { { 2585, 45.9, 65.0 } } }, -- Void-Scarred Eaglet
    [269836] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Chubs
    [270058] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Rope Lynx Harness
    [270061] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Void-Bathed Snapdragon
    [270062] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Void-Touched Chick
    [270063] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Void-Touched Lynx Kitten
    [270191] = { t = "Reward from the achievement Family Battler of Outland", a = 62460 }, -- Lil'Kruul's Hilt
    [270211] = { t = "Reward from the achievement Family Battler of Cataclysm", a = 62461 }, -- Furiostraza's Filter
    [270214] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Poisoned Parasite
    [270248] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Autumn Snapling
    [270249] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Cursed Spawn
    [270250] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Steady Croakfrog
    [270251] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Sleek Snakebiter
    [270252] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Nightfur Kapara
    [270253] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Jaundiced Slitherer
    [270254] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- Caustic Writhling
    [270988] = { t = "Comes in Wriggling Field Pouch, Field Satchel, Wriggling Recruit's Field Pouch" }, -- Wriggling Capybara
    [270990] = { t = "Comes in Wriggling Recruit's Field Pouch, Field Satchel, Wriggling Field Pouch" }, -- Curious Lynx Kitten
    [271185] = { t = "Reward from the quest Like Dragonhawks to a Flame (from Shaja)", at = { { 2437, 55.0, 18.4 } } }, -- Emberlyn
    [273838] = { t = "Reward from the quest The Innocent Essence (from Du'gal)", at = { { 2509, 50.4, 63.4 } } }, -- Spirit of Tok'jara
    [275302] = { t = "Reward from the achievement Gladiator: Midnight Season 2", a = 62930 }, -- Venomous Gladiator's Goredrake
    [275432] = { t = "Reward from the achievement Venomous Combatant", a = 63099 }, -- Vicious Lightbloom Boar
    [275433] = { t = "Reward from the achievement Venomous Combatant", a = 63103 }, -- Vicious Lightbloom Boar
    [275464] = { t = "Comes in Satchel of Chilled Goods" }, -- Sun Festival's Painted Roc
    [275652] = { t = "Reward from the achievement Glory of the Venomous Raider", a = 63254 }, -- Crimson Venomfang
    [275656] = { t = "Reward from the achievement Treasures of the Coiled Isle", a = 63359 }, -- Auriferous Venomfang
    [275657] = { t = "Reward from the achievement Let Me Solo Him: Azta'rec", a = 63333 }, -- Apophic Soul Crusher
    [275683] = { t = "Crafted by a profession (or bought on the Auction House)" }, -- G-00
    [275825] = { t = "Reward from the achievement Tour of Duty: The Coiled Isle", a = 63167 }, -- Ula'tek's Sssacrificial Rain
    [275988] = { t = "Reward from the quest Fangs for the Memories (from Valeera Sanguinar)", at = { { 2393, 52.4, 78.0 } } }, -- Corrosive Victory
    [276234] = { t = "Comes in Wriggling Venom-Soaked Satchel" }, -- Vibrant Venomfang
    [276371] = { t = "Reward from the quest A Frigid Welcome to Val (from Belath Dawnblade)", at = { { 2599, 41.6, 84.6 } } }, -- Lightveil Recall Beacon
    [276553] = { t = "Reward from the achievement Pro Poison Patroller", a = 63653 }, -- Emerald Skyfang
    [276801] = { t = "Reward from the achievement Assault the Vault", a = 63630 }, -- Venomous Coiler
    [276804] = { t = "Found in Zul'jan's Strongbox, Challenger's Cache" }, -- The Writhing Brood
    [276881] = { t = "Reward from the achievement Midnight Keystone Master: Season 2", a = 62447 }, -- Breath of Blight
    [276882] = { t = "Reward from the achievement Midnight Keystone Legend: Season 2", a = 62449 }, -- Breath of Ruin
    [277192] = { t = "Reward from the achievement Umbral Champion: Midnight Season 1", a = 63104 }, -- Umbral Ashes
    [278397] = { t = "Fished up" }, -- Ephemeral Star Ooze
    [279197] = { t = "Found in Slitherfang" }, -- Slitherfang
    [279387] = { t = "Reward from the achievement No Egg Scramble", a = 63609 }, -- Ula'took
    [279483] = { t = "Reward from the quest Tipping the Scaled (from the Three-Eyed Fish, which moves around)", at = { { 2512, 22.0, 65.6 }, { 2512, 22.0, 69.4 }, { 2512, 22.2, 60.6 }, { 2509, 42.2, 23.8 }, { 2509, 42.6, 53.0 }, { 2509, 43.2, 30.8 } } }, -- Three-Eyed Fish
    [280178] = { t = "Found in Unfortunate Scout's Satchel", at = { { 2512, 21.4, 64.3 }, { 2512, 26.3, 54.7 } } }, -- Poison Dart Frog
    [280189] = { t = "Comes in Balanced Offering" }, -- Cauldron Concoction
    [280201] = { t = "Reward from the quest Strong Heart (from Kehiah)", at = { { 2437, 45.2, 48.6 } } }, -- Book of Storytime
    [280305] = { t = "Drops from Latent Cultist, Echo of Jawae" }, -- Soulcoil Remnant
    [280419] = { t = "Reward from the achievement Student of Hissstory", a = 63662 }, -- Cursed Badge of the Soulcoilers
}
